In [1]:
import pandas as pd
import numpy as np

In [2]:
# 문제 1

data = [["KFC", 1000, 4.5], ["McDonald", 2000, 3.9], ["SchoolFood", 2500, 4.2]]
row = [0, 1, 2]
col = ["food", "price", "rating"]

df1 = pd.DataFrame(data=data, index=row, columns=col)

df1

         food  price  rating
0         KFC   1000     4.5
1    McDonald   2000     3.9
2  SchoolFood   2500     4.2

In [9]:
# 문제 2

df2 = df1[["food", "rating"]]

df2

         food  rating
0         KFC     4.5
1    McDonald     3.9
2  SchoolFood     4.2

In [4]:
# 문제 3

df3 = df1.rename({"food": "place"}, axis=1)

df3

        place  price  rating
0         KFC   1000     4.5
1    McDonald   2000     3.9
2  SchoolFood   2500     4.2

In [28]:
df1.select_dtypes(include=['number'])

   price  rating
0   1000     4.5
1   2000     3.9
2   2500     4.2

In [29]:
df1.rename(index={1:"1번"})

          food  price  rating
0          KFC   1000     4.5
1번    McDonald   2000     3.9
2   SchoolFood   2500     4.2